# Generated by Django 4.0.4 on 2023-02-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_univ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Univ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('univ', models.CharField(max_length=50)),
            ],
        ),
    ]
