# Generated by Django 4.0.4 on 2023-02-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_univ'),
    ]

    operations = [
        migrations.AddField(
            model_name='univ',
            name='img',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
