# Generated by Django 4.1.7 on 2023-02-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_univ_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='univ',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
