# Generated by Django 4.0.4 on 2023-02-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_univ_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
        migrations.AddField(
            model_name='question',
            name='q_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/°m/%d'),
        ),
        migrations.AddField(
            model_name='user',
            name='univ',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='univ',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/°m/%d'),
        ),
    ]
