# Generated by Django 4.0.4 on 2023-02-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_question_img_question_q_img_user_univ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univ',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
