# Generated by Django 4.0.4 on 2023-02-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_univ_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
