# Generated by Django 4.1.7 on 2023-02-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_question_q_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='univ',
            name='ans',
            field=models.CharField(default='', max_length=10),
        ),
    ]
