# Generated by Django 4.1.7 on 2023-02-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_univ_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='univ',
            name='ans',
        ),
    ]
