# Generated by Django 4.0.4 on 2023-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_univ_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
