# Generated by Django 4.1.7 on 2023-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_user_univ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='univ',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
