# Generated by Django 4.1.7 on 2023-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_user_univ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='univ',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
