# Generated by Django 4.1.7 on 2023-02-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_question_ans_question_explanation'),
        ('myapp', '0013_alter_user_univ'),
    ]

    operations = [
    ]
